### ISSUE TITLE
DICOM import works too well and never fails

### ISSUE THREAD

**Issue by pierrehenri-dauvergne** [fli-iam/shanoir-ng#1886] opened 2023-09-28 13:55 UTC
I removed a dicom from a zip file (in 'IMAGES' folder) and tried to import without editing the DICOMDIR. It shouldn't work but it does.

**Comment by michaelkain** [comment] 2023-10-23 10:01
Hi Pierre-Henri, I hope you are doing fine. I tested the above behaviour and it is fine on develop. When I delete a file from a serie, the serie is tagged as erroneous and removed from the actual import, but the import continues, in the idea, to import as max the series, that are complete. In case of only one selected serie, that has an error, it might be interesting to test, how the import behaves. I am closing this issue, as the problem is detected and managed.

**Closed by michaelkain** 2023-10-23 10:01 UTC
Labels: bug, import
