### ISSUE TITLE
study members: not confirmed

### ISSUE THREAD

**Issue by solene2020** [fli-iam/shanoir-ng#1091] opened 2021-11-12 13:11 UTC
A UCAN study member says to me that she has no acces to UCAN study for the images import ( access to ICAN previously).
In the sudy member list, I see that  her status is not confirmed.
How can I send her a new confirmation email ?

Thank you !
![shanoir](https://user-images.githubusercontent.com/72256970/141472278-27d99dff-1452-4026-ab1a-db6536f11f42.JPG)
Solène

**Comment by michaelkain** [comment] 2021-11-15 08:59
Hi Solène, the confirmed colum shows, WHEN a **data user agreement (DUA)** is configured (.pdf uploaded to the study), that an user has accepted the DUA. If you DO NOT use DUA, you can ignore it and it has no meaning, so it should not be the problem. Thank you and with kind regards, Michael

**Comment by jcomedouteau** [comment] 2021-11-15 09:02
Hello Solène,
To give access to your user, you can:
1) Edit the study
2) Add a "data user agreement" file.
3) Save the changes
4) Re-edit your study
5) Remove the data user agreement file previously added
6) Save the changes.

This should update the study so that all the users are confirmed. This was due to a previous (now corrected) bug when adding a user.

Have a nice day!

**Comment by solene2020** [comment] 2021-11-15 09:57
Hello, 
Thank you, I understand now.
I followed this steps but when I removed the data user agreement file previously added ( 5.), impossible to update and save the changes !
Help me please :)
All users are now " not confirmed " !

**Comment by solene2020** [comment] 2021-11-15 10:00
ok problem solved, do not take into account my previous message thanks !

**Comment by jcomedouteau** [comment] 2021-11-15 10:04
I noticed the same, the "update" button is not well updated when changing / removing the DUA file, we'll try to correct this !
Tell us if the user can now connect.

Have a nice day,
Jean-Côme

**Comment by michaelkain** [comment] 2021-11-15 10:34
Hi, thx Solène & thx Jean-Come, as Jean-Come has created another issue for the update-button, I will close this issue.

**Closed by michaelkain** 2021-11-15 10:34 UTC
