### ISSUE TITLE
No examinations available on the examinations list

### ISSUE THREAD

**Issue by alexpron** [fli-iam/shanoir-ng#2400] opened 2024-09-06 08:48 UTC
During test session on qualif ofsep, I had subject level data but no examination level data. 
![image](https://github.com/user-attachments/assets/da3300f1-9aa8-4606-9c83-0b81e2d1d39d)

**Comment by jcomedouteau** [comment] 2024-09-09 14:53
Could not reproduce.
We miss details, Maybe you did not have access to any examinations. (as the result is 'no result' and not an error, I guess so).
I'm closing it.

**Closed by jcomedouteau** 2024-09-09 14:53 UTC
