### ISSUE TITLE
import data issue

### ISSUE THREAD

**Issue by solene2020** [fli-iam/shanoir-ng#561] opened 2020-10-05 13:27 UTC
New message on "manage my tasks" : Unexpected error during the import: No enum constant org.shanoir.ng.datasetacquisition.model.mr.MrSequenceVariant.TOF, please contact an administrator.

Thank you!

**Comment by michaelkain** [comment] 2020-10-05 14:41
Caused by: java.lang.IllegalArgumentException: **No enum constant** org.shanoir.ng.datasetacquisition.model.mr.MrSequenceVariant.TOF
	**at java.lang.Enum.valueOf(Enum.java:238)**
	at org.shanoir.ng.datasetacquisition.model.mr.MrSequenceVariant.valueOf(MrSequenceVariant.java:24)
	at org.shanoir.ng.datasetacquisition.model.mr.MrSequenceVariant.getIdByType(MrSequenceVariant.java:91)
	at org.shanoir.ng.datasetacquisition.model.mr.MrProtocolMetadata.setMrSequenceVariant(MrProtocolMetadata.java:283)
	at org.shanoir.ng.importer.strategies.protocol.MrProtocolStrategy.**createOriginMrProtocolMetadata**(MrProtocolStrategy.java:374)
	at org.shanoir.ng.importer.strategies.protocol.MrProtocolStrategy.generateProtocolForSerie(MrProtocolStrategy.java:58)
	at org.shanoir.ng.importer.strategies.datasetacquisition.MrDatasetAcquisitionStrategy.generateDatasetAcquisitionForSerie(MrDatasetAcquisitionStrategy.java:96)
	at org.shanoir.ng.importer.service.DatasetAcquisitionContext.generateDatasetAcquisitionForSerie(DatasetAcquisitionContext.java:63)
	at org.shanoir.ng.importer.service.ImporterService.createDatasetAcquisitionForSerie(ImporterService.java:186)
	at org.shanoir.ng.importer.service.ImporterService.createAllDatasetAcquisition(ImporterService.java:121)
	... 32 common frames omitted

**Comment by michaelkain** [comment] 2020-10-05 14:59
waiting for answer

**Comment by michaelkain** [comment] 2020-10-06 06:38
Solution from @ebannier2018: TOF is a typical official sequence for vessel imaging without contrast agent, it appears in some other fields in the ontology (Angio or NonContrastEnhancedAngio). You can add it to the list but I would rather put **Steady State** instead to stay in line with the standard. I will map TOF to SS.

**Comment by michaelkain** [comment] 2020-10-07 07:24
Hi Solène, I fixed this bug in the code. We will have to test it on our qualif/test environment and it should be deployed and corrected for you beginning of next week. I will close the issue as soon as it is available on shanoir.irisa.fr.

**Comment by michaelkain** [comment] 2020-10-20 09:56
working now, confirmed by SJ by mail

**Closed by michaelkain** 2020-10-20 09:56 UTC
Labels: blocking, import, production, v1.0-necessary, wait-for
