### ISSUE TITLE
Manual processed dataset import fail

### ISSUE THREAD

**Issue by youennmerel** [fli-iam/shanoir-ng#2208] opened 2024-04-26 13:32 UTC
On develop, when trying to import a processed dataset, job fail with error message : 
```
Unexpected error during the import: class java.lang.NullPointerException : Cannot invoke "org.shanoir.ng.datasetacquisition.model.DatasetAcquisition.getExamination()" because the return value of "org.shanoir.ng.dataset.model.Dataset.getDatasetAcquisition()" is null, please contact an administrator.
```

On MS datasets :
```
ofsep-qualif-datasets-1  | 2024-04-26T15:28:57.330+02:00 ERROR 1 --- [nio-9904-exec-7] o.s.ng.importer.service.ImporterService  : Error while importing processed dataset: 
ofsep-qualif-datasets-1  | 
ofsep-qualif-datasets-1  | java.lang.NullPointerException: Cannot invoke "org.shanoir.ng.datasetacquisition.model.DatasetAcquisition.getExamination()" because the return value of "org.shanoir.ng.dataset.model.Dataset.getDatasetAcquisition()" is null
ofsep-qualif-datasets-1  | 	at org.shanoir.ng.dataset.service.DatasetServiceImpl.create(DatasetServiceImpl.java:188)
ofsep-qualif-datasets-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ofsep-qualif-datasets-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
....
ofsep-qualif-datasets-1  | 2024-04-26T15:28:57.335+02:00 ERROR 1 --- [nio-9904-exec-7] o.s.n.s.c.GlobalExceptionHandler         : Unexpected error in the rest service. 
ofsep-qualif-datasets-1  | 
ofsep-qualif-datasets-1  | java.lang.NullPointerException: Cannot invoke "org.shanoir.ng.datasetacquisition.model.DatasetAcquisition.getExamination()" because the return value of "org.shanoir.ng.dataset.model.Dataset.getDatasetAcquisition()" is null
ofsep-qualif-datasets-1  | 	at org.shanoir.ng.dataset.service.DatasetServiceImpl.create(DatasetServiceImpl.java:188)
ofsep-qualif-datasets-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ofsep-qualif-datasets-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
ofsep-qualif-datasets-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ofsep-qualif-datasets-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
...
```

**Comment by jcomedouteau** [comment] 2024-06-03 12:14
Duplicate of #2233
My PR is linked to the other one, I'm closing this one

**Closed by jcomedouteau** 2024-06-03 12:14 UTC
Labels: bug
