### ISSUE TITLE
Import data from DICOM CD/DVD/Unexpected error during the import

### ISSUE THREAD

**Issue by solene2020** [fli-iam/shanoir-ng#555] opened 2020-10-02 11:21 UTC
Error message during import: " Unexpected error during the import: Name is null, please contact an administrator."
![Capture shnaoir ng 02oct20](https://user-images.githubusercontent.com/72256970/94918048-105aad80-04b2-11eb-9ace-6abe6df08528.JPG)

**Comment by michaelkain** [comment] 2020-10-02 13:49
Hi Solène, we will work on this on Monday. Strange, until now all other imports seem to work.

**Comment by michaelkain** [comment] 2020-10-05 07:06
I tested an import with a dicom-zip file on shanoir.irisa.fr right now, and it worked. So no general issue, luckily. I will analyse the logs to figure out, what happened with the import of Solène. @jcomedouteau I will transfer you my findings, so please wait for my analysis, thank you. I am on it.

**Comment by michaelkain** [comment] 2020-10-05 07:18
Events.log: We had 18 successful imports last week on multiple studies, and 2 imports with errors, the two of Solène

**Comment by michaelkain** [comment] 2020-10-05 07:25
Caused by: java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Enum.java:236)
	at **org.shanoir.ng.importer.dto.CoilType.valueOf(CoilType.java:23)**
	at org.shanoir.ng.importer.strategies.protocol.MrProtocolStrategy.createOriginMrProtocolMetadata(MrProtocolStrategy.java:287)
	at org.shanoir.ng.importer.strategies.protocol.MrProtocolStrategy.generateProtocolForSerie(MrProtocolStrategy.java:58)
	at org.shanoir.ng.importer.strategies.datasetacquisition.MrDatasetAcquisitionStrategy.generateDatasetAcquisitionForSerie(MrDatasetAcquisitionStrategy.java:96)
	at org.shanoir.ng.importer.service.DatasetAcquisitionContext.generateDatasetAcquisitionForSerie(DatasetAcquisitionContext.java:63)
	at org.shanoir.ng.importer.service.ImporterService.createDatasetAcquisitionForSerie(ImporterService.java:186)
	at org.shanoir.ng.importer.service.ImporterService.createAllDatasetAcquisition(ImporterService.java:121)

**Comment by michaelkain** [comment] 2020-10-05 07:25
there is a problem with the coil-mapping/resolution

**Comment by michaelkain** [comment] 2020-10-05 07:35
receivingCoil.setCoilType(CoilType.valueOf(receivingCoilType));

**Comment by michaelkain** [comment] 2020-10-05 07:57
I fixed the issue with my commit: commit 47248c163017a462ea9cbf8df78791cd169b9bc6
only if receiving coil type is present, we now try to match it using name and type
with the next production deployment this will be fixed

**Comment by michaelkain** [comment] 2020-10-05 07:59
@solene2020 Hi Solène, I will close this issue as soon as it is available in prod.

**Comment by solene2020** [comment] 2020-10-05 11:22
Hi Mickael,



Thank you!

Can I try to upload again?

Solène Jouan

TEC-UIC imagerie

CHU de Nantes

02 44 76 85 39 (68539) absente le mercredi



________________________________
De : michaelkain <notifications@github.com>
Envoyé : lundi 5 octobre 2020 09:35
À : fli-iam/shanoir-ng
Cc : JOUAN Solene; Author
Objet : Re: [fli-iam/shanoir-ng] Import data from DICOM CD/DVD/Unexpected error during the import (#555)


receivingCoil.setCoilType(CoilType.valueOf(receivingCoilType));

-

**Comment by michaelkain** [comment] 2020-10-06 06:39
solved, deployed on prod 5.10.2020

**Closed by michaelkain** 2020-10-06 06:39 UTC
Labels: blocking, datasets, import, production, subject, v1.0-necessary

**Comment by solene2020** [comment] 2020-10-06 07:35
Hi Mickael,



thank you, no issue this morning for this data.

Solène Jouan

TEC-UIC imagerie

CHU de Nantes

02 44 76 85 39 (68539) absente le mercredi



________________________________
De : michaelkain <notifications@github.com>
Envoyé : mardi 6 octobre 2020 08:39
À : fli-iam/shanoir-ng
Cc : JOUAN Solene; Mention
Objet : Re: [fli-iam/shanoir-ng] Import data from DICOM CD/DVD/Unexpected error during the import (#555)


Closed #555<https://github.com/fli-iam/shanoir-ng/issues/555>.

-

**Comment by michaelkain** [comment] 2020-10-06 09:12
Thank you a lot Solène! Good to hear :-)
